language: php
php:
- 5.6
- 7.0
- 7.1
env:
- WP_VERSION=4.8
- WP_VERSION=latest
before_install:
- git submodule update --init --recursive
- composer install
before_script:
- bash tests/install.sh $WP_VERSION
script: phpunit
